### ISSUE TITLE
signtool

### ISSUE THREAD

**Issue by JSONValidator** [felicienfrancois/node-innosetup-compiler#7]
Tell me please, how can I find signtool.exe and how can I create pfx file on macOS?
Is it possible to sign app with macOS?

**Comment by felicienfrancois** [comment]
Yes, It should be possible.
You will need either signtool.exe copied from a windows installation or another command line signing tool (like [signcode-tf](https://www.npmjs.com/package/signcode-tf))
Then you'll have to pass the sign command line through parameters like in [https://github.com/felicienfrancois/node-innosetup-compiler#command-line](examples). You will probably have to tweak escaping (to prevent evaluation of paths and `$f` in the mac shell) and to tweak the paths (some must be absolute in the wine path system, don't know about slash vs antislash)
Finally, you'll have to add `SignTool=signtool` in the [Setup] section of your iss file to make it use the command.

You may sign with either a self signed certificate (not recommended because Windows with show a security alert to your users) or a valid __Authenticode certificate__ which you can purchase from most certificate reseller.
The generation of the private key and the self signed certificate or the cer to get a valid __Authenticode certificate__ can be done on mac using openssl. You should find the procedure on google
